### ISSUE TITLE
Pull Only Filtered Emails

### ISSUE THREAD

**Issue by wilmajd** [dnschneid/pebblegmail#5]
I want to only read emails that I have filtered with certain labels.  Can this be done?

**Comment by dnschneid** [comment]
I suppose you figured out that you can enter arbitrary gmail search terms in the configuration :)

**Comment by wilmajd** [comment]
Yep, thanks!

--
Wilma Davis
Raytown, MO 64138
wilmajennydavis@gmail.com
Mobile: 816-260-2868 <wilmajennydavis@816-260-2868>
