### ISSUE TITLE
Unable to add new accounts

### ISSUE THREAD

**Issue by benjamin-antupit** [dnschneid/pebblegmail#6]
Hello!
First of all, thanks for making this sweet pebble app! I noticed that when I press "GET KEY" on a new account, I get a Google page with an error. The screenshot is below. Any ideas on how to get around it?
![img_b1c1f680404a-1](https://user-images.githubusercontent.com/15172054/44303922-0f7e5600-a302-11e8-878b-fe3ab183b00d.jpeg)

**Comment by dnschneid** [comment]
Thanks for the kind words! Unfortunately, Google turned down the login flow
this app was using, and I haven't investigated a new approach yet. I'm not
sure if/when I'll get the chance to do so, but I'll post an update when
that happens.

**Comment by dnschneid** [comment]
So it turns out that Google just blacklisted the webview user agent.  I've done a quick tweak to the config page to (silently) copy the auth URL to the clipboard.  If you switch to Chrome and paste in the URL you should be able to get the login key.  I'll improve the experience a bit, but at least now it should be working.

**Comment by benjamin-antupit** [comment]
Hmm. I just tried it today and when I tap "GET URL", I see "URL copied to clipboard" in the text box. However when I switch to safari, it appears that there is nothing on my clipboard. I also tried copying something before tapping "GET URL" and that button does not appear to modify the clipboard because the thing I had previously copied still pasted.

**Comment by dnschneid** [comment]
[Are you on iOS <10?](https://stackoverflow.com/questions/34045777/copy-to-clipboard-using-javascript-in-ios)

**Comment by benjamin-antupit** [comment]
I'm on iOS 11.4.1 (15G77). Maybe double check all the requirements in [this answer](https://stackoverflow.com/a/34046084) or implement the function noted in the answer. Also, could you add a field with the url so I could try manually copying it?

**Comment by dnschneid** [comment]
Yep, that's what I'm thinking too.  For now, I'll just make the URL remain in the auth code text box.
